//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Tests.Api.ApiTests.Locations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocationsFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocationsFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Tests.Api.ApiTests.Locations.LocationsFiles", typeof(LocationsFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   OverrIdes the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:30,&quot;Name&quot;:&quot;Debur and Polish&quot;},{&quot;Id&quot;:60,&quot;Name&quot;:&quot;Final Assembly&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;Finished Goods Storage&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;Frame Forming&quot;},{&quot;Id&quot;:20,&quot;Name&quot;:&quot;Frame Welding&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Metal Storage&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Miscellaneous Storage&quot;},{&quot;Id&quot;:40,&quot;Name&quot;:&quot;Paint&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Paint Shop&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Paint Storage&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Sheet Metal Racks&quot;},{&quot;Id&quot;:45,&quot;Name&quot;:&quot;Specialized Paint&quot;},{&quot;Id&quot;:50,&quot;Name&quot;:&quot;Subassembly&quot;},{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Tool Crib&quot;}]
        ///
        ///.
        /// </summary>
        internal static string GetAll_json {
            get {
                return ResourceManager.GetString("GetAll_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:30,&quot;Name&quot;:&quot;Debur and Polish&quot;},{&quot;Id&quot;:60,&quot;Name&quot;:&quot;Final Assembly&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;Finished Goods Storage&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;Frame Forming&quot;},{&quot;Id&quot;:20,&quot;Name&quot;:&quot;Frame Welding&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Metal Storage&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Miscellaneous Storage&quot;},{&quot;Id&quot;:40,&quot;Name&quot;:&quot;Paint&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Paint Shop&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Paint Storage&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Sheet Metal Racks&quot;},{&quot;Id&quot;:45,&quot;Name&quot;:&quot;Specialized Paint&quot;},{&quot;Id&quot;:50,&quot;Name&quot;:&quot;Subassembly&quot;},{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Tool Crib&quot;}]
        ///
        ///.
        /// </summary>
        internal static string GetAllByNameAsc_json {
            get {
                return ResourceManager.GetString("GetAllByNameAsc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Tool Crib&quot;},{&quot;Id&quot;:50,&quot;Name&quot;:&quot;Subassembly&quot;},{&quot;Id&quot;:45,&quot;Name&quot;:&quot;Specialized Paint&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Sheet Metal Racks&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Paint Storage&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Paint Shop&quot;},{&quot;Id&quot;:40,&quot;Name&quot;:&quot;Paint&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Miscellaneous Storage&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Metal Storage&quot;},{&quot;Id&quot;:20,&quot;Name&quot;:&quot;Frame Welding&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;Frame Forming&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;Finished Goods Storage&quot;},{&quot;Id&quot;:60,&quot;Name&quot;:&quot;Final Assembly&quot;},{&quot;Id&quot;:30,&quot;Name&quot;:&quot;Debur and Polish&quot;}]
        ///
        ///.
        /// </summary>
        internal static string GetAllByNameDesc_json {
            get {
                return ResourceManager.GetString("GetAllByNameDesc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Tool Crib&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Sheet Metal Racks&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Paint Shop&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Paint Storage&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Metal Storage&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Miscellaneous Storage&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;Finished Goods Storage&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;Frame Forming&quot;},{&quot;Id&quot;:20,&quot;Name&quot;:&quot;Frame Welding&quot;},{&quot;Id&quot;:30,&quot;Name&quot;:&quot;Debur and Polish&quot;},{&quot;Id&quot;:40,&quot;Name&quot;:&quot;Paint&quot;},{&quot;Id&quot;:45,&quot;Name&quot;:&quot;Specialized Paint&quot;},{&quot;Id&quot;:50,&quot;Name&quot;:&quot;Subassembly&quot;},{&quot;Id&quot;:60,&quot;Name&quot;:&quot;Final Assembly&quot;}]
        ///
        ///.
        /// </summary>
        internal static string GetAllOrderByIdAsc_json {
            get {
                return ResourceManager.GetString("GetAllOrderByIdAsc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:60,&quot;Name&quot;:&quot;Final Assembly&quot;},{&quot;Id&quot;:50,&quot;Name&quot;:&quot;Subassembly&quot;},{&quot;Id&quot;:45,&quot;Name&quot;:&quot;Specialized Paint&quot;},{&quot;Id&quot;:40,&quot;Name&quot;:&quot;Paint&quot;},{&quot;Id&quot;:30,&quot;Name&quot;:&quot;Debur and Polish&quot;},{&quot;Id&quot;:20,&quot;Name&quot;:&quot;Frame Welding&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;Frame Forming&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;Finished Goods Storage&quot;},{&quot;Id&quot;:6,&quot;Name&quot;:&quot;Miscellaneous Storage&quot;},{&quot;Id&quot;:5,&quot;Name&quot;:&quot;Metal Storage&quot;},{&quot;Id&quot;:4,&quot;Name&quot;:&quot;Paint Storage&quot;},{&quot;Id&quot;:3,&quot;Name&quot;:&quot;Paint Shop&quot;},{&quot;Id&quot;:2,&quot;Name&quot;:&quot;Sheet Metal Racks&quot;},{&quot;Id&quot;:1,&quot;Name&quot;:&quot;Tool Crib&quot;}]
        ///
        ///.
        /// </summary>
        internal static string GetAllOrderedByIdDesc_json {
            get {
                return ResourceManager.GetString("GetAllOrderedByIdDesc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:1,&quot;Name&quot;:&quot;Tool Crib&quot;}.
        /// </summary>
        internal static string GetById_json {
            get {
                return ResourceManager.GetString("GetById_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:60,&quot;Name&quot;:&quot;Final Assembly&quot;},{&quot;Id&quot;:7,&quot;Name&quot;:&quot;Finished Goods Storage&quot;},{&quot;Id&quot;:10,&quot;Name&quot;:&quot;Frame Forming&quot;},{&quot;Id&quot;:20,&quot;Name&quot;:&quot;Frame Welding&quot;}].
        /// </summary>
        internal static string GetByName_json {
            get {
                return ResourceManager.GetString("GetByName_json", resourceCulture);
            }
        }
    }
}
