//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Tests.Api.ApiTests.UnitsMeasure {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UnitsMeasureFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UnitsMeasureFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Tests.Api.ApiTests.UnitsMeasure.UnitsMeasureFiles", typeof(UnitsMeasureFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   OverrIdes the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UnitMeasureCode&quot;:&quot;BTL&quot;,&quot;Name&quot;:&quot;Bottle&quot;},{&quot;UnitMeasureCode&quot;:&quot;BOX&quot;,&quot;Name&quot;:&quot;Boxes&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAN&quot;,&quot;Name&quot;:&quot;Canister&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAR&quot;,&quot;Name&quot;:&quot;Carton&quot;},{&quot;UnitMeasureCode&quot;:&quot;CS &quot;,&quot;Name&quot;:&quot;Case&quot;},{&quot;UnitMeasureCode&quot;:&quot;C  &quot;,&quot;Name&quot;:&quot;Celsius&quot;},{&quot;UnitMeasureCode&quot;:&quot;CM &quot;,&quot;Name&quot;:&quot;Centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CTN&quot;,&quot;Name&quot;:&quot;Container&quot;},{&quot;UnitMeasureCode&quot;:&quot;CR &quot;,&quot;Name&quot;:&quot;Crate&quot;},{&quot;UnitMeasureCode&quot;:&quot;CCM&quot;,&quot;Name&quot;:&quot;Cubic centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CDM&quot;,&quot;Name&quot;:&quot;Cubic decimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;FT3&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAll_json {
            get {
                return ResourceManager.GetString("GetAll_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UnitMeasureCode&quot;:&quot;BOX&quot;,&quot;Name&quot;:&quot;Boxes&quot;},{&quot;UnitMeasureCode&quot;:&quot;BTL&quot;,&quot;Name&quot;:&quot;Bottle&quot;},{&quot;UnitMeasureCode&quot;:&quot;C  &quot;,&quot;Name&quot;:&quot;Celsius&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAN&quot;,&quot;Name&quot;:&quot;Canister&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAR&quot;,&quot;Name&quot;:&quot;Carton&quot;},{&quot;UnitMeasureCode&quot;:&quot;CBM&quot;,&quot;Name&quot;:&quot;Cubic meters&quot;},{&quot;UnitMeasureCode&quot;:&quot;CCM&quot;,&quot;Name&quot;:&quot;Cubic centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CDM&quot;,&quot;Name&quot;:&quot;Cubic decimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CM &quot;,&quot;Name&quot;:&quot;Centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CM2&quot;,&quot;Name&quot;:&quot;Square centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CR &quot;,&quot;Name&quot;:&quot;Crate&quot;},{&quot;UnitMe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOrderByIdAsc_json {
            get {
                return ResourceManager.GetString("GetAllOrderByIdAsc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UnitMeasureCode&quot;:&quot;PT &quot;,&quot;Name&quot;:&quot;Pint, US liquId&quot;},{&quot;UnitMeasureCode&quot;:&quot;PCT&quot;,&quot;Name&quot;:&quot;Percentage&quot;},{&quot;UnitMeasureCode&quot;:&quot;PC &quot;,&quot;Name&quot;:&quot;Piece&quot;},{&quot;UnitMeasureCode&quot;:&quot;PAL&quot;,&quot;Name&quot;:&quot;Pallet&quot;},{&quot;UnitMeasureCode&quot;:&quot;PAK&quot;,&quot;Name&quot;:&quot;Pack&quot;},{&quot;UnitMeasureCode&quot;:&quot;OZ &quot;,&quot;Name&quot;:&quot;Ounces&quot;},{&quot;UnitMeasureCode&quot;:&quot;MM &quot;,&quot;Name&quot;:&quot;Millimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;ML &quot;,&quot;Name&quot;:&quot;Milliliter&quot;},{&quot;UnitMeasureCode&quot;:&quot;MG &quot;,&quot;Name&quot;:&quot;Milligram&quot;},{&quot;UnitMeasureCode&quot;:&quot;M3 &quot;,&quot;Name&quot;:&quot;Cubic meter&quot;},{&quot;UnitMeasureCode&quot;:&quot;M2 &quot;,&quot;Name&quot;:&quot;Square meter&quot;},{&quot;UnitMeasureCode [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOrderByIdDesc_json {
            get {
                return ResourceManager.GetString("GetAllOrderByIdDesc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UnitMeasureCode&quot;:&quot;BTL&quot;,&quot;Name&quot;:&quot;Bottle&quot;},{&quot;UnitMeasureCode&quot;:&quot;BOX&quot;,&quot;Name&quot;:&quot;Boxes&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAN&quot;,&quot;Name&quot;:&quot;Canister&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAR&quot;,&quot;Name&quot;:&quot;Carton&quot;},{&quot;UnitMeasureCode&quot;:&quot;CS &quot;,&quot;Name&quot;:&quot;Case&quot;},{&quot;UnitMeasureCode&quot;:&quot;C  &quot;,&quot;Name&quot;:&quot;Celsius&quot;},{&quot;UnitMeasureCode&quot;:&quot;CM &quot;,&quot;Name&quot;:&quot;Centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CTN&quot;,&quot;Name&quot;:&quot;Container&quot;},{&quot;UnitMeasureCode&quot;:&quot;CR &quot;,&quot;Name&quot;:&quot;Crate&quot;},{&quot;UnitMeasureCode&quot;:&quot;CCM&quot;,&quot;Name&quot;:&quot;Cubic centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CDM&quot;,&quot;Name&quot;:&quot;Cubic decimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;FT3&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOrderByNameAsc_json {
            get {
                return ResourceManager.GetString("GetAllOrderByNameAsc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UnitMeasureCode&quot;:&quot;LB &quot;,&quot;Name&quot;:&quot;US pound&quot;},{&quot;UnitMeasureCode&quot;:&quot;M2 &quot;,&quot;Name&quot;:&quot;Square meter&quot;},{&quot;UnitMeasureCode&quot;:&quot;CM2&quot;,&quot;Name&quot;:&quot;Square centimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;PT &quot;,&quot;Name&quot;:&quot;Pint, US liquId&quot;},{&quot;UnitMeasureCode&quot;:&quot;PC &quot;,&quot;Name&quot;:&quot;Piece&quot;},{&quot;UnitMeasureCode&quot;:&quot;PCT&quot;,&quot;Name&quot;:&quot;Percentage&quot;},{&quot;UnitMeasureCode&quot;:&quot;PAL&quot;,&quot;Name&quot;:&quot;Pallet&quot;},{&quot;UnitMeasureCode&quot;:&quot;PAK&quot;,&quot;Name&quot;:&quot;Pack&quot;},{&quot;UnitMeasureCode&quot;:&quot;OZ &quot;,&quot;Name&quot;:&quot;Ounces&quot;},{&quot;UnitMeasureCode&quot;:&quot;MM &quot;,&quot;Name&quot;:&quot;Millimeter&quot;},{&quot;UnitMeasureCode&quot;:&quot;ML &quot;,&quot;Name&quot;:&quot;Milliliter&quot;},{&quot;UnitMeasur [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAllOrderByNameDesc_json {
            get {
                return ResourceManager.GetString("GetAllOrderByNameDesc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;UnitMeasureCode&quot;:&quot;CAR&quot;,&quot;Name&quot;:&quot;Carton&quot;}.
        /// </summary>
        internal static string GetById_json {
            get {
                return ResourceManager.GetString("GetById_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;UnitMeasureCode&quot;:&quot;CAN&quot;,&quot;Name&quot;:&quot;Canister&quot;},{&quot;UnitMeasureCode&quot;:&quot;CAR&quot;,&quot;Name&quot;:&quot;Carton&quot;},{&quot;UnitMeasureCode&quot;:&quot;CS &quot;,&quot;Name&quot;:&quot;Case&quot;}].
        /// </summary>
        internal static string GetByName_json {
            get {
                return ResourceManager.GetString("GetByName_json", resourceCulture);
            }
        }
    }
}
