//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Tests.Api.ApiTests.ProductSubcategories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductSubcategoriesFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductSubcategoriesFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Tests.Api.ApiTests.ProductSubcategories.ProductSubcategoriesFiles", typeof(ProductSubcategoriesFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:26,&quot;Name&quot;:&quot;Bike Racks&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:27,&quot;Name&quot;:&quot;Bike Stands&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:1,&quot;Name&quot;:&quot;Mountain Bikes&quot;,&quot;ProductCategoryID&quot;:1,&quot;ProductCategoryName&quot;:&quot;Bikes&quot;},{&quot;ID&quot;:2,&quot;Name&quot;:&quot;Road Bikes&quot;,&quot;ProductCategoryID&quot;:1,&quot;ProductCategoryName&quot;:&quot;Bikes&quot;},{&quot;ID&quot;:3,&quot;Name&quot;:&quot;Touring Bikes&quot;,&quot;ProductCategoryID&quot;:1,&quot;ProductCategoryName&quot;:&quot;Bikes&quot;}].
        /// </summary>
        public static string Get_by_subcategoryName_or_categoryName_json {
            get {
                return ResourceManager.GetString("Get_by_subcategoryName_or_categoryName_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:26,&quot;Name&quot;:&quot;Bike Racks&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:27,&quot;Name&quot;:&quot;Bike Stands&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:28,&quot;Name&quot;:&quot;Bottles and Cages&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:29,&quot;Name&quot;:&quot;Cleaners&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:30,&quot;Name&quot;:&quot;Fenders&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:31,&quot;Name&quot;:&quot;Helmets&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAll_json {
            get {
                return ResourceManager.GetString("GetAll_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:26,&quot;Name&quot;:&quot;Bike Racks&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:27,&quot;Name&quot;:&quot;Bike Stands&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:28,&quot;Name&quot;:&quot;Bottles and Cages&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:29,&quot;Name&quot;:&quot;Cleaners&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:30,&quot;Name&quot;:&quot;Fenders&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:31,&quot;Name&quot;:&quot;Helmets&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAllOrderedByCategoryNameAsc_json {
            get {
                return ResourceManager.GetString("GetAllOrderedByCategoryNameAsc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:4,&quot;Name&quot;:&quot;Handlebars&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:5,&quot;Name&quot;:&quot;Bottom Brackets&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:6,&quot;Name&quot;:&quot;Brakes&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:7,&quot;Name&quot;:&quot;Chains&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:8,&quot;Name&quot;:&quot;Cranksets&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:9,&quot;Name&quot;:&quot;Derailleurs&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAllOrderedByCategoryNameDesc_json {
            get {
                return ResourceManager.GetString("GetAllOrderedByCategoryNameDesc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:18,&quot;Name&quot;:&quot;Bib-Shorts&quot;,&quot;ProductCategoryID&quot;:3,&quot;ProductCategoryName&quot;:&quot;Clothing&quot;},{&quot;ID&quot;:26,&quot;Name&quot;:&quot;Bike Racks&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:27,&quot;Name&quot;:&quot;Bike Stands&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:28,&quot;Name&quot;:&quot;Bottles and Cages&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:5,&quot;Name&quot;:&quot;Bottom Brackets&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:6,&quot;Name&quot;:&quot;Brakes&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryN [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAllOrderedByNameAsc_json {
            get {
                return ResourceManager.GetString("GetAllOrderedByNameAsc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:17,&quot;Name&quot;:&quot;Wheels&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:25,&quot;Name&quot;:&quot;Vests&quot;,&quot;ProductCategoryID&quot;:3,&quot;ProductCategoryName&quot;:&quot;Clothing&quot;},{&quot;ID&quot;:16,&quot;Name&quot;:&quot;Touring Frames&quot;,&quot;ProductCategoryID&quot;:2,&quot;ProductCategoryName&quot;:&quot;Components&quot;},{&quot;ID&quot;:3,&quot;Name&quot;:&quot;Touring Bikes&quot;,&quot;ProductCategoryID&quot;:1,&quot;ProductCategoryName&quot;:&quot;Bikes&quot;},{&quot;ID&quot;:37,&quot;Name&quot;:&quot;Tires and Tubes&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:24,&quot;Name&quot;:&quot;Tights&quot;,&quot;ProductCategoryID&quot;:3,&quot;ProductCategoryName&quot;:&quot;Clothing&quot;} [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAllOrderedByNameDesc_json {
            get {
                return ResourceManager.GetString("GetAllOrderedByNameDesc_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ID&quot;:1,&quot;Name&quot;:&quot;Mountain Bikes&quot;,&quot;ProductCategoryID&quot;:1,&quot;ProductCategoryName&quot;:&quot;Bikes&quot;}.
        /// </summary>
        public static string GetBySubcategoryId_json {
            get {
                return ResourceManager.GetString("GetBySubcategoryId_json", resourceCulture);
            }
        }
    }
}
