//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Tests.Api.ApiTests.ProductSubcategories {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ProductSubcategoriesFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductSubcategoriesFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Tests.Api.ApiTests.ProductSubcategories.ProductSubcategoriesFiles", typeof(ProductSubcategoriesFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;ID&quot;:26,&quot;Name&quot;:&quot;Bike Racks&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:27,&quot;Name&quot;:&quot;Bike Stands&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:28,&quot;Name&quot;:&quot;Bottles and Cages&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:29,&quot;Name&quot;:&quot;Cleaners&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:30,&quot;Name&quot;:&quot;Fenders&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName&quot;:&quot;Accessories&quot;},{&quot;ID&quot;:31,&quot;Name&quot;:&quot;Helmets&quot;,&quot;ProductCategoryID&quot;:4,&quot;ProductCategoryName [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GetAll_json {
            get {
                return ResourceManager.GetString("GetAll_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;ID&quot;:1,&quot;Name&quot;:&quot;Mountain Bikes&quot;,&quot;ProductCategoryID&quot;:1,&quot;ProductCategoryName&quot;:&quot;Bikes&quot;}.
        /// </summary>
        public static string GetBySubcategoryId_json {
            get {
                return ResourceManager.GetString("GetBySubcategoryId_json", resourceCulture);
            }
        }
    }
}
