//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Tests.Api.ApiTests.Products {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProductsFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProductsFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Tests.Api.ApiTests.Products.ProductsFiles", typeof(ProductsFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;Id&quot;:879,&quot;Name&quot;:&quot;All-Purpose Bike Stand&quot;,&quot;ProductNumber&quot;:&quot;ST-1401&quot;,&quot;Color&quot;:null,&quot;ListPrice&quot;:159.0000,&quot;ProductSubcategoryId&quot;:27,&quot;ProductSubcategoryName&quot;:&quot;Bike Stands&quot;},{&quot;Id&quot;:712,&quot;Name&quot;:&quot;AWC Logo Cap&quot;,&quot;ProductNumber&quot;:&quot;CA-1098&quot;,&quot;Color&quot;:&quot;Multi&quot;,&quot;ListPrice&quot;:8.9900,&quot;ProductSubcategoryId&quot;:19,&quot;ProductSubcategoryName&quot;:&quot;Caps&quot;},{&quot;Id&quot;:877,&quot;Name&quot;:&quot;Bike Wash - Dissolver&quot;,&quot;ProductNumber&quot;:&quot;CL-9009&quot;,&quot;Color&quot;:null,&quot;ListPrice&quot;:7.9500,&quot;ProductSubcategoryId&quot;:29,&quot;ProductSubcategoryName&quot;:&quot;Cleaners&quot;},{&quot;Id&quot;:843,&quot;Name&quot;:&quot;Cable Lock&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetAll_json {
            get {
                return ResourceManager.GetString("GetAll_json", resourceCulture);
            }
        }
    }
}
